src/main/java/com/ctc/wstx/sw/BaseStreamWriter.java
src/test/java/wstxtest/msv/TestW3CSchemaTypes.java

In our project we use woodstox to validate the stream written to an XMLStreamWriter. 
At first we used the `writeCharacters(char[] text, int start, int len)` method for writing to the XMLStreamWriter. Then validation failed with the message: *ParseError at [row,col]:[5,30] Message: Unknown reason*. When using `writeCharacters(String text)` everything worked fine.
The changes in this pull request should fix this issue.

Fix validation of text for an XMLStreamWriter.

---

src/main/java/com/ctc/wstx/api/ReaderConfig.java
src/main/java/com/ctc/wstx/api/WstxInputProperties.java
src/main/java/com/ctc/wstx/cfg/InputConfigFlags.java
src/main/java/com/ctc/wstx/sr/StreamScanner.java
src/test/java/stax2/stream/TestXML10AllowAllEscapedChars.java

DavMail EWS implementation relies on the wonderful Woodstox Stax parser, with just a small issue: Exchange sends XML 1.0 content with XML 1.1 escaped characters.
Currently DavMail source code includes a patched version of StreamScanner to disable this check, I would really like to drop this patch.
This pull request includes a new custom property com.ctc.wstx.xml10AllowAllEscapedChars to allow XML 1.1 escaped characters in XML content.
Note that this is also related to bug #28

Implement a flag to allow XML 1.1 escaped characters in XML content

---

src/main/java/com/ctc/wstx/api/ReaderConfig.java
src/main/java/com/ctc/wstx/api/WstxInputProperties.java
src/main/java/com/ctc/wstx/cfg/InputConfigFlags.java
src/main/java/com/ctc/wstx/sr/StreamScanner.java
src/test/java/stax2/stream/TestAllowXml11EscapedCharsInXml10.java

As suggested in https://github.com/FasterXML/woodstox/pull/56
Also renamed all properties / methods to match the new name.

Rename P_XML10_ALLOW_ALL_ESCAPED_CHARS property to P_ALLOW_XML11_ESCAPED_CHARS_IN_XML10

---

pom.xml

There is a dependency in OSGi on relaxng, which should be optional.

OSGi dependency on relaxng #85

---

src/main/java/com/ctc/wstx/sw/BufferingXmlWriter.java
src/test/java/wstxtest/msv/TestW3CSchemaTypes.java

In our project we use jackson-dataformat-xml/woodstox to validate the stream written to an XMLStreamWriter.
Some attributes missing right quotes.
The changes in this pull request should fix this issue.

[Fix] Missing closing quotes

---

src/test/java/stax2/stream/TestExtLocationInfo.java

Sorry, didn't wanted to drop the issue #91 without any contribution. But sickness, vacation and lot of work blocked me.
This PR provides the requested minimal failing unit test. Hope it helps.

Unit test for Issue#91

---

pom.xml

unnecessary transitive dependencies
This fixes #96

Do not shade "com.sun.msv.driver.textui" as it drags in a lot of

---

src/main/java/com/ctc/wstx/api/ReaderConfig.java
src/main/java/com/ctc/wstx/sr/BasicStreamReader.java
src/test/java/wstxtest/evt/TestEventReader.java

As discussed in #142, if coalescing was explicitly set to false by the user, text segments may be returned in multiple text events.

Fix #142 (multiple text events for long segments if requested)

---

pom.xml
src/main/java/com/ctc/wstx/dtd/DTDSchemaFactory.java
src/main/java/com/ctc/wstx/msv/RelaxNGSchemaFactory.java
src/main/java/com/ctc/wstx/msv/W3CSchemaFactory.java
src/main/java/com/ctc/wstx/stax/WstxEventFactory.java
src/main/java/com/ctc/wstx/stax/WstxInputFactory.java
src/main/java/com/ctc/wstx/stax/WstxOutputFactory.java
src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory

Add OSGi metadata so that an OSGi framework can consume this bundle's SPI services.
The standard service loader mediator is [Apache Aries SPI-Fly](https://aries.apache.org/documentation/modules/spi-fly.html).

Add standard osgi.serviceloader OSGi metadata for provided services.

---

src/main/java/com/ctc/wstx/dtd/DTDSchemaFactory.java
src/main/java/com/ctc/wstx/msv/RelaxNGSchemaFactory.java
src/main/java/com/ctc/wstx/msv/W3CSchemaFactory.java
src/main/java/com/ctc/wstx/stax/WstxEventFactory.java
src/main/java/com/ctc/wstx/stax/WstxInputFactory.java
src/main/java/com/ctc/wstx/stax/WstxOutputFactory.java

The `osgi.serviceloader.registrar` requirement is satisfied by [Apache Aries SPI-Fly](https://repo1.maven.org/maven2/org/apache/aries/spifly/org.apache.aries.spifly.dynamic.framework.extension), and `java.util.ServiceLoader` _cannot_ work inside an OSGi framework without it.
However, it is probably better to allow people to discover a need for SPI-Fly themselves rather that throwing bundle resolution errors at them when they upgrade `woodstox-core` :blush:.

Declare osgi.serviceloader.registrar requirement as optional.

---

src/main/java/com/ctc/wstx/dtd/DTDSchemaFactory.java
src/main/java/com/ctc/wstx/msv/RelaxNGSchemaFactory.java
src/main/java/com/ctc/wstx/msv/W3CSchemaFactory.java
src/main/java/com/ctc/wstx/stax/WstxEventFactory.java
src/main/java/com/ctc/wstx/stax/WstxInputFactory.java
src/main/java/com/ctc/wstx/stax/WstxOutputFactory.java

Reverts FasterXML/woodstox#155

Fix #163: Revert "Declare `osgi.serviceloader.registrar` requirement as optional"

---

pom.xml

This brutally reconfigures the bundle to make `osgi.serviceloader.registrar` optional again _without_ changing the annotations to use:
```java
@ServiceProvider(..., resolution = Resolution.OPTIONAL)
```
I've asked the Bnd Guys whether there's a better solution, but this should provide anyone who is experiencing problems with something to test.

Declare osgi.serviceloader.registrar to be optional.

---

src/main/java/com/ctc/wstx/dtd/MinimalDTDReader.java
src/test/java/wstxtest/stream/TestComments.java
src/test/java/wstxtest/stream/TestLocation.java

Wrong line for XML event location in elements following DTD
- Added additional comment coverage in TestComments.java
- Added test per Issue #67 writeup to TestLocation.java
- Carriage line was not being checked so it was skipped, added check and call to skipCRLF(c) to advance line number.

Changes / fixes for Issue #67

---

release-notes/CREDITS
release-notes/VERSION
src/moditect/module-info.java

Remove `provides` statements from module definition; hoping this resolves #193.

Try resolve #193: exclude refs to shaded modules

---

pom.xml

Fix shading of isorelax (#200).

Fix shading of isorelax (#200).

---

release-notes/CREDITS
release-notes/VERSION
src/main/java/com/ctc/wstx/stax/WstxEventFactory.java
src/test/java/wstxtest/evt/TestEventFactoryLocation.java

Addresses #204:
-   Ensure events with non-null location
-   Ensure events with non-volatile location
The latter is a secondary issue noted in the original report.

WstxEventFactory: Ensure events' immutable non-null location

---

pom.xml
release-notes/CREDITS
release-notes/VERSION
src/main/java/com/ctc/wstx/sax/WstxSAXParser.java
src/test/java/wstxtest/sax/TestLexicalHandler.java
src/test/resources/wstxtest/sax/eyephone.xml
src/test/resources/wstxtest/sax/productinfo_v1.dtd

This is the pull request for issue #209
It also adds a test case.
One thing that I find problematic at the moment is that it needs an extra configuration on the STAX factory. It would be better if this would either be the default behaviour -- which is a breaking change but might make sense since other SAX parsers behave that way too -- or at least could be controlled via a feature flag.

Add support for LexicalHandler.startEntity and endEntity

---

release-notes/CREDITS
release-notes/VERSION
src/main/java/com/ctc/wstx/sax/WstxSAXParserFactory.java
src/test/java/wstxtest/sax/TestLexicalHandler.java

Hi Tatu,
this is the PR for #211 . I'm looking forward for your feedback :-)
Thanks and kind regards,
Philipp

Disable resolveEntityRefs by default for SAX parsers

---

src/main/java/com/ctc/wstx/sax/WstxSAXParser.java
src/test/java/wstxtest/sax/TestBasicSax.java

Hello,
this is a PR for https://github.com/FasterXML/woodstox/issues/213.
It also modifies one of the SAX tests to test for systemId. The test fails with 7.1.0 and succeeds with 7.1.1-SNAPSHOT. I wasn't totally sure about the naming of the variable locator in the test though. Most of the variables are prefixed with _, I interpreted it that this might indicate public/direct use and went without it for the locator.
feel free to change anything, as you see fit.
Thanks in advance and kind regards,
Philipp

Fix Locator not being fully initialized when setLocator is called

---

release-notes/VERSION
src/main/java/com/ctc/wstx/io/WstxInputData.java
src/test/java/com/ctc/wstx/io/WstxInputDataTest.java

note that *all* 7-bit ASCII chars take the shortcut via LUT now; previously, the chars 7B..7F were taking particularly many branches

(#220) Switch to lookup tables in hotspots `isNameChar()`/`isNameStartChar()`
